spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - name: JwtFilter
      routes:
        - id: auth-server
          uri: lb://JWT-AUTH-SERVER
          predicates:
            - Path=/api/auth/**
            - Method=POST
        - id: products
          uri: lb://PRODUCTS
          predicates:
            - Path=/products/**
            - Method=POST,GET
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-products
          uri: lb://USER-PRODUCTS
          predicates:
            - Path=/user-products/**
            - Method=POST,GET
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://jwt-auth-server/api/auth/login
server:
  port: 8080

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8040/eureka

jwt:
  secret: secret